### ISSUE TITLE
Getting this Error ERROR: executing external native build for cmake

### ISSUE THREAD

**Issue by rajaroni** [igorski/MWEngine#110]
ERROR: executing external native build for cmake D:\MWEngine-master\src\main\cpp\CMakeLists.txt
i am getting this error while building this project  please guide me about this

**Comment by igorski** [comment]
Do you have a stack trace / line number of where the build fails ? What is the build environment you are using ? When using Android Studio you should have most toolchains already available, though note you will have to install the Android NDK separately (can be done from within AS). Note that [SWIG is required and must installed separately and be in your global path](https://github.com/igorski/MWEngine#development-setup).

**Comment by rajaroni** [comment]
thank you fro you reply as i set swig exe file path in environment
variables but still getting this error as i m trying to build on android
studio

Configuration failed.
CMake Error at
D:/Android-Sdk/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137
(message):
  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
Call Stack (most recent call first):

D:/Android-Sdk/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378
(_FPHSA_FAILURE_MESSAGE)

D:/Android-Sdk/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindSWIG.cmake:63
(FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:153 (find_package)

**Comment by rajaroni** [comment]
and here is cmake output file

**Comment by rajaroni** [comment]
please guide me how to set swig for this project as i am getting Could NOT
find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)

**Comment by rajaroni** [comment]
after setting swig now i am getting this error

unable to resolve nl.igorski.mwengine.core.*

as these packages are not import successfully and my java package is
vanish from src folder in project console

**Comment by igorski** [comment]
By default those classes should not be in the repository as they represent the Java wrappers (created through SWIG) to interact with the native layer code.

Have you managed to successfully complete a build ? Running the following Gradle target:

_gradle externalNativeBuildRelease_

should compile the native layer code. Can you verify whether this step has completed successfully and afterwards that the folder _/src/main/java/nl/igorski/mwengine/core_ is generated and contains .java files ?

If you are using Android Studio there is a known issue that it will not recognize these files, closing and reopening the project should be enough (on subsequent builds this will not be an issue).

**Comment by rajaroni** [comment]
As i already done above step but core files are not generated

**Comment by rajaroni** [comment]
As i have seen core package in android window but not showing in project
window i switch project to android window but still no success

**Comment by rajaroni** [comment]
Yes *src/main/java/nl/igorski/mwengine/core is created but only in android
window not available in Project window as unable to import *
*src/main/java/nl/igorski/mwengine/core.**

**Comment by igorski** [comment]
What is the exact OS, NDK and SWIG versions you are using ?

**Comment by rajaroni** [comment]
NDK version is 21.0.6113669 
SWIG is 4.0.1
OS Windows 7
Android Studio 3.4.1
