### ISSUE TITLE
Cannot find Java classes in nl.igorski.mwengine.core

### ISSUE THREAD

**Issue by rajaroni** [igorski/MWEngine#111]
After Setting Swig Getting this error as above package is unable to import.

**Comment by igorski** [comment]
Closing as this duplicates #112 please report OS, NDK and SWIG version in there.

**Comment by rajaroni** [comment]
Swig 3.0.12 and ndk r21

**Comment by igorski** [comment]
Thanks, and what Operating System and its version?

**Comment by rajaroni** [comment]
Operating system windows 7 64bit

**Comment by igorski** [comment]
Your NDK version is fine, if you have used Android Studio to install CMake you'll likely have version 3.10.x which is also fine, I doubt there is an issue with Android Studio or the Android SDK itself.

I'm thinking that the Java files have been generated fine (as you state), but in their implementation they reference an unsupported feature (making AS think the files contain errors, and therefor cannot be imported).

Can you try using the latest version of Swig (4.0.1) which you can get from the [SWIG homepage](http://www.swig.org/download.html) (note the separate link for the Windows installer) ? Version 4 has improved a lot of support for C++14 code, which is what MWEngine uses.

**Comment by rajaroni** [comment]
Now i update my swig version to 4.0.1 but still same error 
My android studio version is 3.4.1 and OS is window 7 
does updating android studio to 3.6.1 may help ?
