### ISSUE TITLE
Cannot able to import  core package globally.

### ISSUE THREAD

**Issue by syedateeb1** [igorski/MWEngine#112]
I have integrated the swig and my project and cmake files are successfully build. I can even access the core files but when i try to import it globally in the class it gaves me error. see screenshot for more understanding
![image](https://user-images.githubusercontent.com/53823697/75950607-760a9b00-5ecb-11ea-8356-ea405b3f3ad9.png)

**Comment by igorski** [comment]
Strange. What OS and IDE are you using?

**Comment by syedateeb1** [comment]
Windows 7 and android studio

**Comment by igorski** [comment]
What is the version of SWIG you are using ? Please try using the latest version 4.0.1 which can be downloaded from the [SWIG website](http://www.swig.org/download.html) (note the separate URL for a Windows installer). This version of SWIG provides extended support for C++14 which is used by MWEngine. My guess is that the Java files have been generated fine but that their implementation is referencing an unsupported feature, making Android Studio consider them unusable.

**Comment by rajaroni** [comment]
![image](https://user-images.githubusercontent.com/14906738/76286395-dfbbe800-62c3-11ea-8522-882f8045a653.png)
getting same error as there is core package inside java folder

**Comment by igorski** [comment]
I managed to recreate this in a VM for the Windows version. Looks like the generated Java classes do not acknowledge their package location to be appropriate for their folder location.

Right clicking on the core folder in the project panel and doing _Mark directory as > Unmark as sources root _ has resolved the issue for me. Can you verify whether it addresses your issue as well ?

**Comment by syedateeb1** [comment]
Thanks . it worked

**Comment by syedateeb1** [comment]
<3
