### ISSUE TITLE
audio glitches in example app

### ISSUE THREAD

**Issue by harthorst** [igorski/MWEngine#120]
I recently updated to master branch (fresh git clone) and discovered audio glitches similar to issue 114.

A screen record can be found here: https://mega.nz/file/Jgk0mQAK#06d-0_CD9WNaeHTyKOqILFpMcWvN-2EEh1SAVkQFlJg

What I did:
1) git clone ...
2) created local.properties
3) changed minSdkVersion to 23 (otherwise the build fails)
4) installed debug.apk

I tried to record the MWEngine output directly but the recorded wav file is only 44k.

**Comment by igorski** [comment]
Issue is treated as relation to #119 

Observed on devices using _Snapdragon 660 processor_ (arm64-v8a ABI), seems thread frequency scaling that has been implemented in the engine might be more appropriate for Intel processors. Affects usage of AAudio driver rather than OpenSL.
