### ISSUE TITLE
Audio glitching on a real device.

### ISSUE THREAD

**Issue by Riobener** [igorski/MWEngine#129]
Hello again! I keep working with your library and all this time doing this on the android emulator. When I tried to run my app on a real device, it got weird clicks when live playing. Here is example, where i compared  your mikrowave app which is using same engine, and my app: [https://drive.google.com/file/d/1ah7Udv6W9pfzLj9Sx5ghFOE0ZE0lgMXB/view?usp=sharing](https://drive.google.com/file/d/1ah7Udv6W9pfzLj9Sx5ghFOE0ZE0lgMXB/view?usp=sharing)
My code just using all the same, as mwengine example, just with my simple synth code:
```
synth = new SynthInstrument();
        synth.getOscillatorProperties(0).setWaveform(0);
        synth.getAudioChannel().setVolume(.7f);
```
It is working perfeclty almost on all emulators that i tried. 
My phone is Samsung A71.
Sry, if this question already was asked.

**Comment by Riobener** [comment]
Ok, it was problem with the driver. I forgot to change it. Now it is working fine with OpenSL driver.. 
Sad, that it is all working bad with AAudio...

**Comment by Riobener** [comment]
> For the AAudio issue, could you verify whether the library version in feature branch [native-thread](https://github.com/igorski/MWEngine/tree/native-thread) solves this issue for your device ? It addresses thread performance tuning specifically for AAudio.
> 
> For the pops, sine waves do indeed have this behaviour. What happens is that when the next note plays (for instance when you slide from C to C#), the C# note starts it slope which overlaps with the slope of the previous C note (which is now in its release phase). The cumulative effect of these create a jump in amplitude known as DC offset. This can be filtered in numerous ways, but often the solution can be simpler.
> 
> Could you experiment by setting the attack of the synths ADSR to a very small positive value, say 0.01f for the sine wave ?

Well, sadly it didnt fix the AAudio issue.  I tried to run example app from native-thread branch, but the result has not changed. 

About sine wave, i tried 0.01f and smaller, or higher value, it makes the same effect. Also i tried each combination parameters of ADSR and still not working.

**Comment by igorski** [comment]
I'll make some time to investigate the sine wave issue, I think it might be a side effect from the "multi timbral eyboard" example I gave you as I think the on/off phases aren't behaving as they should.

For the AAudio issue, I am intrigued as said branch offers improvement on my test devices though I am aware that on the Android eco system there isn't a "one size fits all" solution. Out of interest, what is the exact device you are testing on ? Also, would you consider compiling the code again but with the following change:

If you can comment out line 61 of _global.h_ (which contains _#define PREVENT_CPU_FREQUENCY_SCALING_) prior to building, does this have a notable difference on your device ?

**Comment by Riobener** [comment]
> I'll make some time to investigate the sine wave issue, I think it might be a side effect from the "multi timbral keyboard" example I gave you as I think the on/off phases aren't behaving as they should.
> 
> For the AAudio issue, I am intrigued as said branch offers improvement on my test devices though I am aware that on the Android eco system there isn't a "one size fits all" solution. Out of interest, what is the exact device you are testing on ? Also, would you consider compiling the code again but with the following change:
> 
> If you can comment out line 61 of _global.h_ (which contains _#define PREVENT_CPU_FREQUENCY_SCALING_) prior to building, does this have a notable difference on your device ?

I apologize for such a long answer, I was busy... Yeah, i tried to comment out line 61, but this, according to my feelings, does not bring any result. 

My phone is also - Samsung A71, with Snapdragon 730.
I'll attach a link just in case : [amazon](https://www.amazon.com/Samsung-SM-A715F-Caribbean-Cameras-Android/dp/B084GBC1KH)

I am completely ready to test any performance of your application on my phone in the future. :)

**Comment by igorski** [comment]
No worries on the wait, I'm already happy you have pointed out this issue and are willing to

> completely ready to test any performance of your library on my phone in the future

:smiling_imp:

If I may ask, could you conduct a test where you experience the glitching (does it by the way happen on occasion or is the glitching / clicking audible throughout ?)

If you could record a .wav of the output and also record the logcat output of all messages starting with `AAudio_IO::` that would be a tremendous help. I have an assumption what could be the case and would like to confirm it with the audio file and the logs.

**Comment by Riobener** [comment]
Great job, @igorski! Everything sounds the same now. I understood your explanation, but it's still interesting that the same driver works differently everywhere :)
I'll ask just in case, before creating a new topic, is it okay in this section (on the github issues) to discuss questions about the engine's capabilities and the future , or is it more preferable to write only about bugs or improvements? I just have some several questions about some current engine capabilites and and still unrealized.

**Comment by igorski** [comment]
Good to hear @Riobener !

I'll clean the branch and merge it to master over the coming days as it marks a large stability improvement. I'll keep this issue open to tackle the sine wave popping.

If you have more questions, the GitHub issues are a great spot to out them in, whether big reports or feature requests. I would suggest creating a unique issue per request/bug report as it makes for easier housekeeping and history. :)

**Comment by Riobener** [comment]
Oh, I'm a bad tester. I used to check pulse wave and apparently did not hear that the problem is still exist in sequencer events. The problem completely disappeared from live events.

**Comment by igorski** [comment]
🤦‍♂️  quite right.

There was a separate buffer management between sequenced and live synth events. This has been equalized. The aforementioned branch has been update with this new code.

The good news is that the synthesizer instrument now consumes less memory as temporary buffer management is now handled by the instrument and not the individual events.

**Comment by igorski** [comment]
Note the _native-thread_ branch has been merged into master and deleted.

**Comment by Riobener** [comment]
> Note the _native-thread_ branch has been merged into master and been deleted. This because the state of that branch provided a much more performant engine. 

Good update. All works good. 
However, after refreshing MWEngine, Swig just wrote that in 177 line of CMake file, swig_add_module is deprecated and that I should instead use swig_add_library, so i just change this:
`swig_add_module(${target}_wrapped java ${CPP_SRC}/mwengine.i)`
on this
`swig_add_library(${target}_wrapped LANGUAGE java SOURCES ${CPP_SRC}/mwengine.i)`
and build after that was successful,
My SWIG version is 4.0.2. 

This is a minor error, but I decided to warn you.

**Comment by igorski** [comment]
Good to hear we finally tackled this issue!

Thanks for pointing out the deprecated function, I have just pushed your change using `swig_add_library` to the repository.
