### ISSUE TITLE
swig question

### ISSUE THREAD

**Issue by scar20** [igorski/MWEngine#132]
I just have to "reset" Windows 10 (big pain) so any apps have been reinstalled from scratch. 
Do I need to manually install swig? Because it seem that its kind of integrated with cmake; when I rebuilded a project, there was comments in graddle about swig and it compiled fine. So what is the status about this?
And also, is the situation is the same on the mac? I had a friend that tried to run the app but run into problem instead because it seem it misses some components but I dont know his settings for sure - we've done that by phone with a shared screen so...
I will have to go present a demo of the work done and they all have just macs so I'll will like to know about swig on the mac. It is a required separate install or it will be included in the ndk/cmake setup?

Thanks and I really appreciate your commitment

**Comment by scar20** [comment]
I just checked in my path and I can confirm that swig is not there.

**Comment by igorski** [comment]
Hi, I depends a little on your tooling setup.

On MacOS SWIG does not come preinstalled (if you use a package manager like Brew it's a breeze to install) but it did on my Ubuntu distribution.

SWIG is supported by CMake as a module, but is not part of the CMake toolchain natively.
