### ISSUE TITLE
Different behavior on shared methods (SynthEvent/SampleEvent)

### ISSUE THREAD

**Issue by vustav** [igorski/MWEngine#146]
event.positionEvent(pos) works as intended on SampleEvents but on SynthEvents they play at full steps, ex. a SynthEvent set to play at 3 1/4 will play at 3 etc.

**Comment by vustav** [comment]
Noticed now that after using synthEvent.setEventStart(posInSamples) they will play at the right position one time, then settling at the nearest full step before. This means I can get around this by updating positions every time the sequencer is at 0.

Still strange and as I said it works fine on SampleEvents so I don't think I'm using it the wrong way.

**Comment by igorski** [comment]
This has been addressed in f592455cb26921d952abb737094f28f75102a9cf

Can you verify whether this addresses the issue in the context of your application ? You don't need to update the event positions whenever the sequencer is at the zero offset.

**Comment by vustav** [comment]
Works perfect now!

**Comment by igorski** [comment]
Excellent! Thanks so much for pointing out the issue.
