### ISSUE TITLE
Terminating with uncaught exception of type std::out_of_range: vector

### ISSUE THREAD

**Issue by YogarajRamesh** [igorski/MWEngine#154]
Hi @igorski ,
   
  ### I am trying to add “**reverb**” to my recorded voice, while trying to add reverb I get the Following **error**,
-------------------------------------------------------------------------------------------------------------------------
E/libc++abi: terminating with uncaught exception of type std::out_of_range: vector
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 19536 (AudioTrack), pid 19124 (wengine.example)
-------------------------------------------------------------------------------------------------------------------------
But when I trying to add “**delay**” it **works fine.**

Here is the code snippet

JavaUtilities.createSampleFromFile(
        "output1", Environment.getExternalStorageDirectory().getAbsolutePath() + "/Download/test/output1.wav");
 JavaUtilities.createSampleFromFile(
        “Mahi”, Environment.getExternalStorageDirectory().getAbsolutePath() + "/Download/samps/mahi.wav");
        drumEvent1 = new SampleEvent(_sampler);
        drumEvent.setSample(SampleManager.getSample("output1"));
        _sampler.getAudioChannel().getProcessingChain().addProcessor(reverb);
        drumEvent1 = new SampleEvent(_sampler1);
        drumEvent1.setSample(SampleManager.getSample("mahi"));
        drumEvent.play();
        drumEvent1.play();

I also attached my whole MainActivity.java

https://mega.nz/file/AMUUVB7Q#lMs9MLufhKSR_OJCTpHYdxcCBCLak0j-OUFxeKuNE8c

please suggest a way to add reverb.
Thank you in advance.
@igorski @teotigraphix @robtize

**Comment by igorski** [comment]
Hi @YogarajRamesh like the README states, `please do not send e-mails through the development website`. Creating a GitHub issue is sufficient and will grab my attention. Also no need to tag individual (past) contributors.

I shall have a look at your activity and see what is going on. It might take a few days before issues are resolved because there are other priorities, but they are addressed eventually.

**Comment by YogarajRamesh** [comment]
Thank you for Reply,
Looking forward to resolve this issue. We are also trying our best.

**Comment by igorski** [comment]
This should be addressed in 40ed839cf3c385153853836f5e454e723069420c

**Comment by YogarajRamesh** [comment]
Hi @igorski 
Thank you for your time.
This issue is resolved

**Comment by YogarajRamesh** [comment]
Hi @igorski ,
When I am trying to add Reverb (not reverb) to input channel it again get crashed with same error.
But when I OUTPUT_CHANNELS = 2. It works better.

Code snippet
reverb1 = new Reverb( 0.f, 0.f, 0.f, 0.5f );
_engine.getInputChannel().getProcessingChain().addProcessor(reverb1);

**Comment by igorski** [comment]
Duplicates #159
