### ISSUE TITLE
Is it possible to remove effects after recorded the audio?

### ISSUE THREAD

**Issue by YogarajRamesh** [igorski/MWEngine#157]
Hi @igorski 

**Like you said I am able to add effect to live microphone input.**

**MWEngine.getInputChannel().getProcessingChain().addProcessor(reverb);**

The effect is works fine. **But I want to save the raw audio( with out effects ).**
How can remove the reverb effect which already merged in output file?
Or is there any way to save the file without effect in it?

**Comment by igorski** [comment]
Well, you can't remove the reverb. So short answer is no :)

But I think you could probably could benefit from the choice of specifying whether you want to record the input pre-mix (before the effects chain) or post-mix (after the effects chain, which is the current case).

**Comment by YogarajRamesh** [comment]
Thank you @igorski

**Comment by igorski** [comment]
Maybe I wasn't clear with my reply 😅  _it's not possible now, but I will invest some time in making it possible_.

I have reopened the issue just so we can keep track of it.

**Comment by YogarajRamesh** [comment]
😀thank you so much @igorski

**Comment by igorski** [comment]
This has been implemented in e0a6287df4e65b8a45d55080ed4f190155d04b67

You now need to pass a boolean value to the input recording method. When true, the ProcessingChain of the input channel is omitted (you will hear the effects applied in the output, but the recorded input is completely dry). When false, this records with the effects of the input channel applied.

`MWEngine.startInputRecording( outputFileName, true )`

**Comment by YogarajRamesh** [comment]
Hi @igorski ,

Thank you for this feature. it works really well.

**Comment by igorski** [comment]
Good to hear, it's also a nice addition the engines features so thanks for the suggestion!
