### ISSUE TITLE
Bug with processingChain.removeProcessor(fx) 

### ISSUE THREAD

**Issue by vustav** [igorski/MWEngine#158]
I've managed to isolate the reason for a crash I've had for a while down to removal of effects from the processing chain. One feature in my app removes all effects from an instrument and adds a randomized number of new ones. I used to do this by looping through the array with the effects and removing them one by one from the processing chain, but sometimes one of them stayed anyway. Using reset() on the chain fixes this, but the strange behavoir when removing them one by one in a loop is obviuosly still there.

**Comment by igorski** [comment]
This has been addressed in fdab12a9a9825c5595388a3585708ca11817a6be by using vector find-iterator based removal instead of looping.

**Comment by vustav** [comment]
Sorry for the late answer. Working now!
