### ISSUE TITLE
Noise While adding effects to input channel

### ISSUE THREAD

**Issue by YogarajRamesh** [igorski/MWEngine#162]
Hi @igorski ,

I am trying to add effects(mostly all the effects) to the input channel during live recording. it **produce noise** in output file. With out effects output files are smooth(with out noise).

I have attached both without and with effects sample files.

```
 private ReverbSM reverb;
  reverb = new ReverbSM();
_engine.getInputChannel().getProcessingChain().addProcessor(reverb);
```

song with effect
https://mega.nz/file/gUc1UCaa#L81EjrElTzf77cojvz5ytrbF5eTVBgv1_NqirYKJtZA
song without effect
https://mega.nz/file/tcNVmQBK#YO3G2Dsxr-bnI25Nj730vNz7p-d83tT4fr_fswJrtgo

Thanks in advance @igorski

**Comment by igorski** [comment]
Sounds like your input signal is hot. A little fail safe clamping has been added in b32043472c086a694f5abdeae2aea4ced3981997 but you might consider adding a Limiter instance to the ProcessingChain of the input channel (as the last effect in the chain).
