### ISSUE TITLE
Crashing when deleting events with the engine running

### ISSUE THREAD

**Issue by vustav** [igorski/MWEngine#173]
In another issue I have started I was reminded that for a while I haven't actually deleted events when the engine is running because of crashes. Instead I've used a class that I send them to after removing them from the sequencer to be deleted when the sequencer stops. Today I tried deleting them right away and the crashes are still there. These are the steps:

for(events){
  event.enable(false);
  event.removeFromSequencer();
  event.delete();
}
instrument.getAudioChannel().getProcessingChain().reset();
instrument.getAudioChannel().getProcessingChain().delete();
instrument.delete();

This is the stack from firebase:

![deleteEvents](https://user-images.githubusercontent.com/8558260/181640802-8effb726-4512-40b3-89c9-dddfde2c61a9.png)

**Comment by igorski** [comment]
Continued in #179
