### ISSUE TITLE
cannot resolve symbol 'nativeaudio'

### ISSUE THREAD

**Issue by NingJinBo** [igorski/MWEngine#26]
where is you libs nativeaudio,cannot resolve symbol 'nativeaudio'?

**Comment by igorski** [comment]
Hi @NingJinBo the Java wrappers are not part of the repository and have to be generated using the Android NDK.

Run the _build.sh_ (Unix) or _build.bat_ (Windows) file in the root of the repository to generate the _nl.igorski.lib.nativeaudio_ namespace.
