### ISSUE TITLE
Is the MWEngine suitable for multitrack daw?

### ISSUE THREAD

**Issue by uc3po** [igorski/MWEngine#27]
Hi,
I'm trying to implement a ordinary multitrack daw.

E.g i have 12 Tracks, 
Each tracks have different time range with seconds 
(track1: 0-45, track2: 10-30,..., track12: 120-150)

Can the MWengine play files with time manipulation?
thanks.

**Comment by igorski** [comment]
Hi, what do you exactly mean by time manipulation ?

Judging from your example, each track has content starting and ending at different points and with different durations. This is perfectly feasible in MWEngine.

Each track can have its own dedicated Instrument (which in turn will give it its own dedicated AudioChannel). Each of these instruments can have their own events. If the audio you're playing is a sample, you can create a SampleEvent and position it (_setStartPosition()_, _setEndPosition()_, _setDuration()_) as you please.

When in doubt, you can consult the Wiki pages on : 

[Instruments](https://github.com/igorski/MWEngine/wiki/Instruments)
[AudioEvents](https://github.com/igorski/MWEngine/wiki/AudioEvents)

**Comment by uc3po** [comment]
Thanks for reply.
