### ISSUE TITLE
Error:(12, 1) error: package nl.igorski.lib.audio.nativeaudio does not exist

### ISSUE THREAD

**Issue by pradeep2929** [igorski/MWEngine#28]
i download project and just open in Android studio after fetching above error in Activity. please help me 
![screen shot 2017-08-18 at 11 51 10 am](https://user-images.githubusercontent.com/7380977/29446766-999a70f6-840b-11e7-84fc-7c6c5f965fab.png)

**Comment by igorski** [comment]
Hi,

you need to run the makefile which can be done by the build scripts in the repository's root. See "Build instructions" in the README.md file. After building the native library, the Java classes are also generated.

**Comment by pradeep2929** [comment]
Thanks above issue is resolved but fetching new Error 


 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/nl.igorski.example-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]] couldn't find "libmwengine.so"

**Comment by pradeep2929** [comment]
thanks issue is resolve.
