### ISSUE TITLE
Custom c++ observer is not receiving notifications 

### ISSUE THREAD

**Issue by rckrdstrgrd** [igorski/MWEngine#33]
When trying to use a custom observer in c++, no notification is received. 

The problem seems to be in two places. 

1. It's not possible to override  the observer functions `handleNotification(int aNotificationType)` and `handleNotification(int aNotificationType, int aValue)` because these are not declared as `virtual` in `observer.h`. When these functions later are called the parent functions will be invoked, the `virtual` declaration is needed to achieve late binding of these functions. 

2. The vector list of observers in [notifier.cpp](https://github.com/songsterr/MWEngine/blob/master/jni/messaging/notifier.cpp#L48
) will never be filled. This line: 
`std::vector<Observer*> observers = it->second;`
will create a copy of the observer vector, and subsequent calls to `observers.push_back( aObserver );` will be executed on the copy and not the vector in the map. Calling `push_back` directly on `it->second` will work.

**Comment by igorski** [comment]
Great catch! Taken the liberty to take your fixes from your fork into a merge. See https://github.com/igorski/MWEngine/pull/34
