### ISSUE TITLE
_engine.dispose lets crash app when called 2 times

### ISSUE THREAD

**Issue by harthorst** [igorski/MWEngine#48]
How to reproduce:
1) start the example app (hitting play button not necessary)
2) send app in background
3) bring the app back in foreground (everything seems still fine)
4) send it in background again
5) bring it back in foreground
6) now the gui is not responding anymore and the app crashes after some seconds

Phone: Sony Z3 Compact
OS: 6.0.1, BN: 23.5.A.1.291

**Comment by igorski** [comment]
Nice catch, quite embarassing as _dispose()_ should only be called when deliberately destroying the engine (rather than pausing it). This has been addressed in https://github.com/igorski/MWEngine/pull/49.
