### ISSUE TITLE
Unable to control measure subdivision

### ISSUE THREAD

**Issue by hypeastrum** [igorski/MWEngine#5]
aStepsPerBar parameter in updateMeasures method seem to has no effect.
Subdivision seems to be controlled by AudioEngine::beat_subdivision which is not modifiable from API.
Sequencer always notifies about 16 steps.

**Comment by igorski** [comment]
@hypeastrum nice find! If you could fetch the repository and check out the "measure-subdivision" branch. Note that sequencer_controller.h now has a method "updateStepsPerBar" (this method is also invoked on setLoopRange and updateMeasures).

If the given steps per bar differ from the current setting, the engines beat_subdivision is updated to match the given steps for the given time signature.

Does this resolve the issue ?

**Comment by hypeastrum** [comment]
It seems to work fine now. Thanks a lot for quick fix!

**Comment by igorski** [comment]
Merged to master. :)
