### ISSUE TITLE
SampleEvent seems to play files not in correct speed

### ISSUE THREAD

**Issue by harthorst** [igorski/MWEngine#50]
What I did:
        final SampleEvent drumEvent = new SampleEvent( _sampler );
        drumEvent.setSample( SampleManager.getSample( "2"));
        //drumEvent.setPlaybackRate(0.9f);
        drumEvent.setVolume(1f);
        drumEvent.play();

The played tone is a little bit higher than it should be. When I set the playback rate to 0.9 it's almost perfect. 
I tried resampling the wav file (44100 <-> 48k) but that did not help.

Tested on Sony Xperia Z3 Compact

**Comment by igorski** [comment]
Resampling the file is not recommended as different Android devices run at a different native sample rate (unless you check for the sample rate and choose the appropriate sample at the appropriate sample rate).

However, the difference between 44.1 kHz and 48 kHz is negligible so this is not a recommended practice. Instead, specify the sample's sample rate in the overloaded _setSample( AudioBuffer, int )_ method. This will adjust the samples playback rate automatically to make it play at the original speed in the appropriate environment, also see: https://github.com/igorski/MWEngine/wiki/Pitch-shifting-and-resampling-samples#resampling

Updating the original 'working with sample based content'-doc to reflect this.

**Comment by igorski** [comment]
Cool! :thumbsup:
