### ISSUE TITLE
example app crashes when screen is rotated

### ISSUE THREAD

**Issue by harthorst** [igorski/MWEngine#53]
I run the example app, started the sequencer and rotated the screen. 

Logcat output:

09-29 21:02:29.943 24187 24214 D MWENGINE: seq. position: 11, buffer offset: 216, elapsed samples: 66456
09-29 21:02:29.964 24187 24214 E libOpenSLES: frameworks/wilhelm/src/itf/IBufferQueue.c:57: pthread_mutex_lock_timeout_np returned 110
09-29 21:02:29.975 24187 24187 D MWENGINE: initing MWEngineActivity
09-29 21:02:29.975 24187 24187 D AndroidRuntime: Shutting down VM
09-29 21:02:29.976 24187 24187 E AndroidRuntime: FATAL EXCEPTION: main
09-29 21:02:29.976 24187 24187 E AndroidRuntime: Process: nl.igorski.example, PID: 24187
09-29 21:02:29.976 24187 24187 E AndroidRuntime: java.lang.Error: MWEngine already instantiated
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at nl.igorski.lib.audio.MWEngine.<init>(MWEngine.java:110)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at nl.igorski.example.MWEngineActivity.init(MWEngineActivity.java:80)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at nl.igorski.example.MWEngineActivity.onCreate(MWEngineActivity.java:68)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6285)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4176)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at android.app.ActivityThread.access$1000(ActivityThread.java:154)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:234)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-29 21:02:29.976 24187 24187 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-29 21:02:29.981   925  3341 D ActivityManager: New dropbox entry: nl.igorski.example, data_app_crash, a024b8ad-0efb-4d27-a227-485d05b4bc49
09-29 21:02:29.984   925  3341 W ActivityManager:   Force finishing activity nl.igorski.example/.MWEngineActivity
09-29 21:02:30.009 23810 24256 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1271 android.content.ContextWrapper.bindService:604 com.sonyericsson.crashmonitor.MiscTaAdapter.open:90 com.sonyericsson.crashmonitor.service.CrashMonitorService.onInit:127 com.sonyericsson.crashmonitor.service.CrashMonitorService.onHandleIntent:192 
09-29 21:02:30.018   925  2731 I OpenGLRenderer: Initialized EGL, version 1.4
09-29 21:02:30.040 24187 24214 D MWENGINE: seq. position: 12, buffer offset: 954, elapsed samples: 71994
09-29 21:02:30.095 16523 20542 E AsyncOperation: serviceID=40, operation=LogOperation
09-29 21:02:30.095 16523 20542 E AsyncOperation: OperationException[Status{statusCode=Storage full, resolution=null}]
09-29 21:02:30.095 16523 20542 E AsyncOperation: 	at oqf.a(:com.google.android.gms@13280017@13.2.80 (040306-211705629):87)
09-29 21:02:30.095 16523 20542 E AsyncOperation: 	at wwk.run(:com.google.android.gms@13280017@13.2.80 (040306-211705629):29)
09-29 21:02:30.095 16523 20542 E AsyncOperation: 	at bdbk.run(:com.google.android.gms@13280017@13.2.80 (040306-211705629):2)
09-29 21:02:30.095 16523 20542 E AsyncOperation: 	at qcr.run(:com.google.android.gms@13280017@13.2.80 (040306-211705629):21)
09-29 21:02:30.095 16523 20542 E AsyncOperation: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-29 21:02:30.095 16523 20542 E AsyncOperation: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-29 21:02:30.095 16523 20542 E AsyncOperation: 	at qiv.run(:com.google.android.gms@13280017@13.2.80 (040306-211705629))
09-29 21:02:30.095 16523 20542 E AsyncOperation: 	at java.lang.Thread.run(Thread.java:818)
09-29 21:02:30.098 16523 20542 E AsyncOperation: serviceID=40, operation=LogOperation
09-29 21:02:30.098 16523 20542 E AsyncOperation: OperationException[Status{statusCode=Storage full, resolution=null}]
09-29 21:02:30.098 16523 20542 E AsyncOperation: 	at oqf.a(:com.google.android.gms@13280017@13.2.80 (040306-211705629):87)
09-29 21:02:30.098 16523 20542 E AsyncOperation: 	at wwk.run(:com.google.android.gms@13280017@13.2.80 (040306-211705629):29)
09-29 21:02:30.098 16523 20542 E AsyncOperation: 	at bdbk.run(:com.google.android.gms@13280017@13.2.80 (040306-211705629):2)
09-29 21:02:30.098 16523 20542 E AsyncOperation: 	at qcr.run(:com.google.android.gms@13280017@13.2.80 (040306-211705629):21)
09-29 21:02:30.098 16523 20542 E AsyncOperation: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-29 21:02:30.098 16523 20542 E AsyncOperation: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-29 21:02:30.098 16523 20542 E AsyncOperation: 	at qiv.run(:com.google.android.gms@13280017@13.2.80 (040306-211705629))
09-29 21:02:30.098 16523 20542 E AsyncOperation: 	at java.lang.Thread.run(Thread.java:818)
09-29 21:02:30.122   925  1020 I WindowManager: Screen frozen for +271ms due to Window{f2a59ad u0 NavigationBar}
09-29 21:02:30.161 24187 24214 D MWENGINE: seq. position: 13, buffer offset: 732, elapsed samples: 77532
09-29 21:02:30.283 24187 24214 D MWENGINE: seq. position: 14, buffer offset: 510, elapsed samples: 83070
09-29 21:02:30.400 24187 24214 D MWENGINE: seq. position: 15, buffer offset: 288, elapsed samples: 88608
09-29 21:02:30.401 24187 24214 D MWENGINE: seq. position: 0, buffer offset: 292, elapsed samples: 0

**Comment by igorski** [comment]
This is due to Activity's being recreated when the Android system detects an orientation change. MWEngine does not allow multiple instances of itself and would throw an Error. Updated the example Activity to call _engine.dispose()_ upon _onDestroy()_ so the engine could be recreated when the new Activity launches _onCreate()_ for its new orientation.

When dealing with music making applications, you'd likely want to lock your applications orientation to only support a single mode to prevent starting/stopping audio.

**Comment by harthorst** [comment]
Thanks for the explanation.
