### ISSUE TITLE
sometimes sound is interrupted for a few ms

### ISSUE THREAD

**Issue by harthorst** [igorski/MWEngine#57]
there are some sound glitches from time to time. in the log I see:

IBufferQueue.c:57: pthread_mutex_lock_timeout_np returned 110

Google says that's a general problem but maybe you have some hints to prevent this. My app is using up to 5% of cpu power and I'm working with SampleEvents only.

**Comment by igorski** [comment]
Hi, this is a tough one to crack as it lies outside of the engine's reach.
The fact that your app is very low on CPU resources would indicate that there is no issue with threading priority, can you do the same check for memory allocation using a profiler (the one in Android Studio is great for this) ? Also, can you verify whether there are other applications in the background that could be generating audio (most other music making applications could be expected to use OpenSL as well).

**Comment by teotigraphix** [comment]
I have this as well testing on Nexus 7 2nd Gen.

I profiled and memory and CPU seem fine, CPU for the app is not even about 5-10%.

This was also with nothing running(apps in background)

**Comment by harthorst** [comment]
Just for the record: Increasing buffer size helped a lot.
