### ISSUE TITLE
Bounced WAVs should be merged.

### ISSUE THREAD

**Issue by igorski** [igorski/MWEngine#59]
When bouncing the engine's audio output, as long as there is content to be generated, the engine will write a .WAV file at the length of the specified maximum buffer size. At the end of the operation this leaves us with a lot of split .WAV files on the device. These should be merged into a single file.

**Comment by teotigraphix** [comment]
I'm curious, is this just a feature you wrote and never finished?

If the framework doesn't concatenate the slices, what use are they?

You have a direction to send me in a direction for this one? I might be able to do this if I know exactly where it should be done.

Bear with me, I will have this whole framework memorized soon. :)

**Comment by igorski** [comment]
The reason for this "solution" is that recording can be stopped at any time, thus making the total recording length only known when recording has stopped. The problem is that the length of the recording needs to be present in the header of the resulting .WAV file. For existing applications, the WAVs would be merged outside of the engine once recording has stopped. This is of course a little silly as you'd expect this goodness out of the box.

Once recording is stopped (via SequencerController) and the final buffer is written onto file storage, there should be a final operation (through WavWriter) where the written buffers are written one by one into a single .WAV file (and deleted as soon as they have been written).

**Comment by teotigraphix** [comment]
> This is of course a little silly as you'd expect this goodness out of the box

Not really, I was intuitively thinking the Java layer for this, so I can get it. :)

**Comment by igorski** [comment]
Well you could perform the logic inside the MWEngine class and merge the WAVs from there. I do think the benefit from doing in the engine is that it would also work for users who are working solely in C(++). Then again, for recordings with a large duration this could stall the rendering of audio, so ideally it would be performed in a separate thread anyways...

**Comment by teotigraphix** [comment]
Ok, well I am still getting "correct" with proper C++ implementation so I cannot say that some of this stuff I would try might not cut the mustard quite yet. 

I can figure it out native, I guess I misunderstood something your wrote above.

**Comment by igorski** [comment]
Adressed in https://github.com/igorski/MWEngine/pull/92
