### ISSUE TITLE
NDK build version

### ISSUE THREAD

**Issue by teotigraphix** [igorski/MWEngine#60]
Hi,

I was just curious what version of the NDK you are building this with?

Mike

**Comment by igorski** [comment]
Hi Mike, this has been built with NDK versions 8 - 16. Not tested it with current version (18) personally yet. Are you experiencing an isue?

**Comment by teotigraphix** [comment]
Hey!

Well I am up and running right now but I had to download NDK16 to get it to work, I have NDL18 installed with the SDK.

I have to say, what you have here is gold and I am going to be on this for sure. You really made a dream come true for me with all the pieces together here, fantastic!

I have a bunch of apps in mind and I hope to help you out with the project when I get into it more. Right now I use the Caustic audio engine for my apps, but this will be great to try my own audio framework where I can add things from the lab.

**Comment by igorski** [comment]
Thanks for the compliment, hope it is of use to you :)

I will have a look at NDK 18 support though as there is no reason it shouldn't compile. Will keep this issue open until its resolved.

**Comment by igorski** [comment]
Resolved in https://github.com/igorski/MWEngine/pull/69

**Comment by teotigraphix** [comment]
Check! Pulled, Compiled, Perfect!
