### ISSUE TITLE
Oboe integration

### ISSUE THREAD

**Issue by teotigraphix** [igorski/MWEngine#62]
Was wondering now that it's production ready if you were going to integrate it.

I have a couple demos I have compiling that is working with the stream and callbacks.

I wouldn't know how to get it in this project correctly at this point and time of my learning. :)

**Comment by igorski** [comment]
Quite frankly, not entirely sure if that is worth pursuing. While Oboe is great, under the hood it is using OpenSL and AAudio as the driver for output just like MWEngine is doing. Granted, it would be great to leave Oboe to deal with this lowest level the audio programming, but on the short term I don't see this something that should be on the roadmap.

**Comment by teotigraphix** [comment]
Ok,

Still getting my feet wet and what you said validated what I thought.

Oboe is an abstraction layer you have pretty much implemented already.
