### ISSUE TITLE
Audio Driver for Windows

### ISSUE THREAD

**Issue by teotigraphix** [igorski/MWEngine#65]
Hey,

I know you read the title and said, huh? :)

What I was wondering is if it's basically a process of writing a new driver that hooked into something like FMOD library to get this running on Windows.

I use multi-platform libraries for some apps and was curious if I could get this running on the desktop for testing. (UI is multi-platform)

It seems from looking through the source code, even with a new driver it's invasive to the framework? What I mean is you have flags for SL and AA Audio, those are kind of hard coded in the engine it seems?

Thanks

**Comment by igorski** [comment]
Heh, I actually snorted when I read the title :)

It shouldn't actually be wholly intrusive...

OpenSL and AAudio are hard coded in the sense that a definition for their name exists (as provided by _global.h_). The actual inclusion of the libraries and their code are provided by _DriverAdapter_. If you can provide a Windows specific driver (ASIO, WASAPI, DirectAudio, whatever) you can write the custom implementation for getting the input stream and writing the output streams right within DriverAdapter.

Further changes required will be to update the make files to exclude the Android specific, and include the Windows specific libraries.

There are some utiilties though that require android specific libraries, such as _debug.cpp_ (to log messages to the Android logcat) and _javautilities.cpp_ (to access the Android Asset Manager). A search for _#include <android/_ should provide you better insights on the overall impact.

MWEngine has been created specifically for Android, and while the majority of the engine code is actually platform agnostic, I think a Windows (or rather non-Android specific) source/build configuration might be more appropriate in a fork.

**Comment by teotigraphix** [comment]
Yeah thanks for the info!

Exactly what I was asking, it's not worth doing since as I guessed there are a bunch of things tied to Android (log etc.).

I just have a huge amount of UI code and I am thinking about just saying oh well and create a new ui framework for my stuff in java.

Well I have a fork so if I get adventurous someday, I will let you know.

**Question**, Are you making any DSP optimizations because it's Android? Or is the DSP code you have for the core actors pretty much run of the mill DSP.

**Comment by igorski** [comment]
There are no Android specific optimizations, especially as the amount of CPU architectures are wide and varied. It's generic math using generic optimization practices. Most of the real optimizations are likely performed by the compiler when the library is being built for the appropriate architecture.
