### ISSUE TITLE
Sample - Runtime Permissions

### ISSUE THREAD

**Issue by teotigraphix** [igorski/MWEngine#67]
I am pretty sure a comment or something should be added that as of Nov 1st, all apps must be compiled with API 26 or greater to be released on the play store.

The sample app does not handle run-time file access and crashes on non debug devices.

This is not asking to add the code since it's a sample but some people may scratch their heads.

**Comment by igorski** [comment]
Addressed in https://github.com/igorski/MWEngine/pull/69
