### ISSUE TITLE
SampledInstrument event clearEvents/removeEvent methods has no effect

### ISSUE THREAD

**Issue by hypeastrum** [igorski/MWEngine#7]
Methods updateEvents(), clearEvents() and removeEvent() are not implemented in sampledinstrument.cpp. It makes SampledInstrument unusable from Java.

**Comment by igorski** [comment]
@hypeastrum See my answer on https://github.com/igorski/MWEngine/issues/10 as it basically involves the same answer when concerning the removal of a single AudioEvent. I shall refactor the updateEvents() and clearEvents() methods into the BaseInstrument class as the inheriting classes don't have any custom overrides.

**Comment by igorski** [comment]
@hypeastrum I have updated the BaseInstrument to take care of this, you should now be able to use it for SampledInstrument too. Please pull the master branch. Also updated the Wiki and unit tests accordingly.
