### ISSUE TITLE
Example app does not play sound anymore after going into background on Xiaomi Mi Pad 4

### ISSUE THREAD

**Issue by harthorst** [igorski/MWEngine#75]
I installed a fresh version of MWEngine example app on my Mi Pad 4. App starts like expected and plays sound. After going into background and foreground again the device remains silent. Even hitting the Play button several times does not help. Killing the app and starting it again works.

Android version: 8.1.0

**Comment by harthorst** [comment]
Seems like the second call of DriverAdapter::create() failes. The debugger stopped at opensl_io.c line 356:
notifyThreadLock(p->outlock);

Unfortunately I'm not very familar with C but maybe that helps you. Please let me know if I can support you here. I at least have 2 devices which are making trouble :)

**Comment by igorski** [comment]
Closing this as it is completely related to a fix done for https://github.com/igorski/MWEngine/issues/55 (OpenSL destruction routine did not nullify _outlock_)
