### ISSUE TITLE
Add support for non-16 bit WAV assets

### ISSUE THREAD

**Issue by igorski** [igorski/MWEngine#78]
Loading .WAV files from the APK's packaged assets currently only supports 16-bit WAV files, support should be extended for any bit rate.

**Comment by teotigraphix** [comment]
Are you looking to write your own wav code parsing using OS code/library and then implement?

**Comment by igorski** [comment]
WAVs are parsed by the engine already (apart from the header its all raw PCM values that can easily be processed), there is an oversight where the block size is assumed at 16-bits instead of deriving this from the bit rate defined in the header (which ironically, is read).

**Comment by igorski** [comment]
Addressed in https://github.com/igorski/MWEngine/pull/96
