### ISSUE TITLE
Arpeggiator - How To

### ISSUE THREAD

**Issue by teotigraphix** [igorski/MWEngine#81]
Hey!

I have been studying this code and cannot seem to understand how or what triggers the Arppegiator.

Simple setup;

```
       synth1.setArpeggiatorActive(true);
        synth1.getArpeggiator().setAmountOfSteps(16);
        synth1.getArpeggiator().setShiftForStep(0, 1);
        synth1.getArpeggiator().setShiftForStep(1, 1);
        synth1.getArpeggiator().setShiftForStep(2, 5);
        synth1.getArpeggiator().setShiftForStep(3, 1);
        synth1.getArpeggiator().setShiftForStep(4, 1);
        synth1.getArpeggiator().setShiftForStep(5, 7);
        synth1.getArpeggiator().setShiftForStep(6, 1);
        synth1.getArpeggiator().setShiftForStep(7, 1);
        synth1.getArpeggiator().setShiftForStep(8, 10);
        synth1.getArpeggiator().setShiftForStep(9, 1);
        synth1.getArpeggiator().setShiftForStep(10, 1);
        synth1.getArpeggiator().setShiftForStep(11, 6);
        synth1.getArpeggiator().setShiftForStep(12, 1);
        synth1.getArpeggiator().setShiftForStep(13, 1);
        synth1.getArpeggiator().setShiftForStep(14, 1);
        synth1.getArpeggiator().setShiftForStep(15, 1);
```
I get what it's doing but I can't get it to do it. :) I have sequenced 1 audio event for a synth for 8 steps in a 16 step grid for tests.

I also have the sequencer controller playing.

**Comment by igorski** [comment]
You forgot to said a step size (note how I totally rephrased "I forgot to document this thing properly" ;) )

What you did so far is absolutely correct:

_SynthInstrument.setArpeggiatorActive()_ will instruct the Synthesizer that arpeggios need to be applied on synthesis.

_setAmountOfSteps()_ specifies how many steps the Arpeggiator can cycle through before returning to the first.

_setShiftForStep()_ basically specifies the semitones to shift the pitch by (second argument, can be negative as well) for which arpeggiator step (first argument), step must be within range of the total defined step amount.

Now the missing bit is _ setStepSize()_ which accepts an integer value describing the amount of buffer samples to process before shifting to the next step. This is the same value as used for event position and duration (you can similarly use the "_float beat_"-logic here). E.g. at a 44.1 kHz sample rate and tempo of 120 BPM, to make the arpeggiator step once per beat / quarter note you specify the step size as:

```
arpeggiator.setStepSize(( 44100 * 60 ) / 120 );
```

**Comment by teotigraphix** [comment]
Thanks Igor, that makes sense. :)

**Comment by igorski** [comment]
Moved discussion here into its own [Wiki article](https://github.com/igorski/MWEngine/wiki/Module---Arpeggiator) for future reference.
