### ISSUE TITLE
Feature request: add volume control to SampleEvent

### ISSUE THREAD

**Issue by hypeastrum** [igorski/MWEngine#9]
I need to control volume of each (sample) event, to make accents. With current API I can achieve it with many samples with adjusted volume in buffers (memory overhead) or many instruments with different volumes (not flexible, code overhead).
I suggest to add volume control to all events, like in SynthEvent.

**Comment by igorski** [comment]
Good point! Volume should be available to any type of AudioEvent. Each inheriting class can then decide how to interpret it (e.g. to swap samples depending on volume threshold / use different synthesis routines, or simply just scale the output volume (default), etc.).

I have added a branch "event-volumes" to the repository. In this branch _volume has moved to the BaseAudioEvent class and should be available to all AudioEvent-classes. You can use the getVolume() and setVolume( float ) methods everywhere. The mixing of the buffers into the AudioChannel has been updated to us the _volume value of the event.

If you can review whether this meets your request, we can merge it to master.

**Comment by hypeastrum** [comment]
It works fine. Exact for my request.
